# -*- coding: utf-8 -*-
"""att.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxmkycTJy_hWrWbkDKo1nO3WKLlh7-Uz
"""

import streamlit as st
from datetime import datetime

st.set_page_config(page_title="📸 Camera Capture Demo")

st.title("📷 Take a Live Photo")
st.markdown("This is a trial demo to test live photo capture using Streamlit.")

# Live camera input
img_data = st.camera_input("Take a picture")

if img_data:
    st.success("✅ Photo captured!")
    st.image(img_data, caption=f"Captured at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", use_column_width=True)
else:
    st.info("Please take a photo using your device camera.")